In [1]:
import numpy as np
import torch

In [ ]:
arr=np.array([1,2,3])
t1 = torch.from_numpy(arr)
t2 = torch.as_tensor(arr)
t3 = torch.tensor(arr)



tensor([1, 2, 3])
<class 'torch.Tensor'>


In [3]:
print(t1)

tensor([1, 2, 3])


In [4]:
print(type(t1))

<class 'torch.Tensor'>


In [5]:
print(t2)

tensor([1, 2, 3])


In [6]:
print(type(t2))

<class 'torch.Tensor'>


In [7]:
print(t3)
print(type (t3))

tensor([1, 2, 3])
<class 'torch.Tensor'>


In [9]:
arr=np.array([1,2,3],dtype=np.int32)
torch.from_numpy(arr).dtype

torch.int32

In [10]:
torch.tensor(arr)

tensor([1, 2, 3], dtype=torch.int32)

In [12]:
a=torch.tensor(5)
b=torch.tensor([1,2,3])
c=torch.tensor([[1,2,3],[4,5,6]])
d=torch.rand((2,3,4))


In [15]:
print(c.shape)
print(c.dtype)
print(c.ndim)

torch.Size([2, 3])
torch.int64
2
